plugin:
  name: fylr_example
  version: "2"
  l10n: l10n/example-loca.csv
  webfrontend:
    url: FylrExample.js
    css: FylrExample.css
    html: FylrExample.html
  custom:
    henk: denk
  displayname:
    de-DE: FYLR-Example
    en-US: FYLR-Example

base_url_prefix: "webfrontend"

extensions:
  dump/empty:
    exec:
      service: "node"
      commands:
        - prog: "node"
          stdin:
            type: "body"
          stdout:
            type: "body"
          args:
            - type: "value"
              value: "%_exec.pluginDir%/server/extension/empty.js"

  dump/empty2:
    exec:
      service: "node"
      commands:
        - prog: "node"
          stdin:
            type: "body"
          args:
            - type: "value"
              value: "%_exec.pluginDir%/server/extension/empty.js"

  dump/sleep:
    exec:
      service: "python3"
      commands:
        - prog: "python3"
          stdout:
            type: "body"
          args:
            - type: "value"
              value: "%_exec.pluginDir%/server/extension/sleep.py"

  dump/info:
    exec:
      service: "node"
      commands:
        - prog: "node"
          stdin:
            type: "body"
          stdout:
            type: "body"
          args:
            - type: "value"
              value: "%_exec.pluginDir%/server/extension/dump_info.js"
            - type: "value"
              value: "%info.json%"

  dump/error:
    exec:
      service: "node"
      commands:
        - prog: "node"
          stdin:
            type: "body"
          stdout:
            type: "body"
          args:
            - type: "value"
              value: "%_exec.pluginDir%/server/extension/error.js"

  dump/hello:
    exec:
      service: "exec"
      commands:
        - prog: "%_exec.pluginDir%/server/extension/hello/hello-%_exec.GOOS%-%_exec.GOARCH%.exe"
          stdin:
            type: "body"
          stdout:
            type: "body"
          args:
            - type: "value"
              value: "World !"
            - type: "value"
              value: "%info.json%"

  dump/error2:
    exec:
      service: "node"
      commands:
        - prog: "node"
          stdin:
            type: "body"
          stdout:
            type: "body"
          args:
            - type: "value"
              value: "%_exec.pluginDir%/server/extension/error2.js"

  dump/error3:
    exec:
      service: "node"
      commands:
        - prog: "node"
          stdin:
            type: "body"
          stdout:
            type: "body"
          args:
            - type: "value"
              value: "%_exec.pluginDir%/server/extension/error3.js"

  dump/file:
    exec:
      service: "node"
      commands:
        - prog: "node"
          stdin:
            type: "body"
          stdout:
            type: "body"
          args:
            - type: "value"
              value: "%_exec.pluginDir%/server/extension/stdin_to_file.js"
            - type: "value"
              value: "/tmp/record.log"
            - type: "value"
              value: "%info.json%"

  webhook/set_comment:
    exec:
      service: "node"
      commands:
        - prog: "node"
          stdin:
            type: "body"
          stdout:
            type: "body"
          args:
            - type: "value"
              value: "%_exec.pluginDir%/server/db_pre_save+webhook/set_comment.js"
            - type: "value"
              value: "%info.json%"

  webhook/check:
    exec:
      service: "node"
      commands:
        - prog: "node"
          stdin:
            type: "body"
          stdout:
            type: "body"
          args:
            - type: "value"
              value: "%_exec.pluginDir%/server/db_pre_save+webhook/check.js"

  render/standard_extended:
    exec:
      service: "python3"
      commands:
        - prog: "python3"
          stdin:
            type: "body"
          stdout:
            type: "body"
          args:
            - type: "value"
              value: "%_exec.pluginDir%/server/extension/render/standard_extended.py"
            - type: "value"
              value: "%info.json%"

callbacks:
  export_transport:
    copy_file:
      exec:
        timeoutSec: 60
        service: "node"
        commands:
          - prog: "node"
            stdout:
              type: body
            args:
              - type: "value"
                value: "%_exec.pluginDir%/server/export_transport/copy_file.js"
              - type: "value"
                value: "%info.json%"
    module_missing:
      exec:
        timeoutSec: 120
        service: "node"
        commands:
          - prog: "node"
            stdout:
              type: body
            args:
              - type: "value"
                value: "%_exec.pluginDir%/server/export_transport/_missing_.js"
    error:
      exec:
        timeoutSec: 60
        service: "node"
        commands:
          - prog: "node"
            stdout:
              type: body
            args:
              - type: "value"
                value: "%_exec.pluginDir%/server/export_transport/error.js"
              - type: "value"
                value: "%info.json%"

  export:
    module_missing:
      exec:
        timeoutSec: 120
        service: "node"
        commands:
          - prog: "node"
            stdout:
              type: body
            args:
              - type: "value"
                value: "%_exec.pluginDir%/server/export/_missing_.js"
    md5_sums:
      exec:
        timeoutSec: 120
        service: "node"
        commands:
          - prog: "node"
            stdout:
              type: body
            args:
              - type: "value"
                value: "--max-http-header-size=1000000"
              - type: "value"
                value: "%_exec.pluginDir%/server/export/md5_sums.js"
              - type: "value"
                value: "%info.json%"
    error:
      exec:
        timeoutSec: 120
        service: "node"
        commands:
          - prog: "node"
            stdout:
              type: body
            args:
              - type: "value"
                value: "%_exec.pluginDir%/server/export/error.js"
              - type: "value"
                value: "%info.json%"

  transition_db_pre_save:
    set_comment:
      exec:
        service: "node"
        commands:
          - prog: "node"
            stdin:
              type: body
            stdout:
              type: body
            args:
              - type: "value"
                value: "%_exec.pluginDir%/server/db_pre_save+webhook/set_comment.js"
    check:
      exec:
        service: "node"
        commands:
          - prog: "node"
            stdin:
              type: body
            stdout:
              type: body
            args:
              - type: "value"
                value: "%_exec.pluginDir%/server/db_pre_save+webhook/check.js"

  db_pre_save:
    steps:
      - name: "set comment for 'object'"
        callback: set_comment
        filter:
          type: objecttype
          objecttypes:
            - object
            - objects
      - name: "write event with info about inserted and updated objects"
        callback: write_event
        filter:
          type: objecttype
          objecttypes:
            - write_event
      - name: "bounce json back for 'bounce'"
        callback: bounce
        filter:
          type: objecttype
          objecttypes:
            - bounce
      - name: "check 'name' field"
        callback: check
        filter:
          type: objecttype
          objecttypes:
            - photographer
      - name: "validation errors example"
        callback: validation_errors
        filter:
          type: objecttype
          objecttypes:
            - validation_errors

    callbacks:
      validation_errors:
        exec:
          service: "node"
          commands:
            - prog: "node"
              stdin:
                type: body
              stdout:
                type: body
              args:
                - type: "value"
                  value: "%_exec.pluginDir%/server/validation_errors/validation_errors.js"
      bounce:
        exec:
          service: "node"
          commands:
            - prog: "node"
              stdin:
                type: body
              stdout:
                type: body
              args:
                - type: "value"
                  value: "%_exec.pluginDir%/server/db_pre_save+webhook/cat.js"
      set_comment:
        exec:
          service: "node"
          commands:
            - prog: "node"
              stdin:
                type: body
              stdout:
                type: body
              args:
                - type: "value"
                  value: "%_exec.pluginDir%/server/db_pre_save+webhook/set_comment.js"
      write_event:
        exec:
          service: python3
          commands:
            - prog: python3
              stdin:
                type: body
              stderr:
                type: body
              stdout:
                type: body
              args:
                - type: value
                  value: "%_exec.pluginDir%/server/db_pre_save+write_event/write_event.py"
      check:
        exec:
          service: "node"
          commands:
            - prog: "node"
              stdin:
                type: body
              stdout:
                type: body
              args:
                - type: "value"
                  value: "%_exec.pluginDir%/server/db_pre_save+webhook/check.js"

base_config:
  - name: comment
    parameters:
      value:
        type: text
        position: 0
  - name: custom
    parameters:
      on_off:
        type: bool
      data:
        type: json

system_rights:
  - name: example_right
    comment: this right was added by the FYLR example plugin
    parameters:
      - name: bool
        type: bool
      - name: int
        type: int
      - name: text
        type: text
      - name: string-list
        type: string-list
        choices: [ a, b, c ]
      - name: string-list-one
        type: string-list-one
        choices: [ a, b, c ]
      - name: string-list-one-or-zero
        type: string-list-one-or-zero
        choices: [ a, b, c ]
      - name: mask-select
        type: mask-select
      - name: objecttype-select
        type: objecttype-select
      - name: eas-column-select
        type: eas-column-select
      - name: pool-select
        type: pool-select
      - name: preview-versions
        type: preview-versions

custom_types:
  example:
    mapping:
      textfield:
        type: text_oneline
      numberfield:
        type: number
      locafield:
        type: text_l10n
      doublefield:
        type: double
      geofield:
        type: geo_json
    config:
      schema:
        - name: fylr_example_config
          parameters:
            value:
              type: bool
      mask:
        - name: fylr_example_config
          parameters:
            value:
              type: bool
    update:
      exec:
        service: "node"
        commands:
          - prog: "node"
            stdin:
              type: body
            stdout:
              type: body
            args:
              - type: "value"
                value: "%_exec.pluginDir%/customDataTypeUpdater/update.js"
              - type: "value"
                value: "%info.json%"
      timeout: 60
      batch_size: 10
      expires_days: 1

fas_config:
  produce_config: fas_config/custom_produce.yml
  cookbooks:
    - fas_config/cookbook_metadata_example.yml
    - fas_config/cookbook_metadata_pdf2text.yml
    - fas_config/cookbook_grayscale.yml

custom_events:
  EXAMPLE_PLUGIN_OBJECT_STATISTICS:
    user: true
  FYLR_EXAMPLE_EVENT:
    user: true
