// Generated by CoffeeScript 1.12.7
var FylrExampleTransition,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

FylrExampleTransition = (function(superClass) {
  extend(FylrExampleTransition, superClass);

  function FylrExampleTransition() {
    return FylrExampleTransition.__super__.constructor.apply(this, arguments);
  }

  FylrExampleTransition.prototype.getListViewColumn = function() {
    return {
      type: CUI.Output,
      text: "Comment"
    };
  };

  FylrExampleTransition.prototype.getSaveData = function() {
    var sd;
    sd = {
      type: FylrExampleTransition.getType(),
      info: {
        comment: "horst"
      }
    };
    return sd;
  };

  FylrExampleTransition.getType = function() {
    return "fylr_example:set_comment";
  };

  FylrExampleTransition.getDisplayName = function() {
    return "Comment";
  };

  return FylrExampleTransition;

})(TransitionActionAction);

TransitionAction.registerAction(FylrExampleTransition);
