// Generated by CoffeeScript 1.12.7
var FylrExampleCustomDataModelSettings,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

FylrExampleCustomDataModelSettings = (function(superClass) {
  extend(FylrExampleCustomDataModelSettings, superClass);

  function FylrExampleCustomDataModelSettings() {
    return FylrExampleCustomDataModelSettings.__super__.constructor.apply(this, arguments);
  }

  FylrExampleCustomDataModelSettings.prototype.getCustomSettings = function(data) {
    var fields;
    fields = [
      {
        type: CUI.Input,
        name: "fylr_example",
        placeholder: "example",
        form: {
          label: "example setting"
        },
        data: data.custom_settings
      }
    ];
    return fields;
  };

  FylrExampleCustomDataModelSettings.prototype.getCustomSettingsLabel = function(data) {
    return "FYLR example";
  };

  FylrExampleCustomDataModelSettings.prototype.getCustomSettingsDisplay = function(data) {
    if (data.custom_settings.fylr_example) {
      return ["FYLR example"];
    }
  };

  return FylrExampleCustomDataModelSettings;

})(SchemaPlugin);

Schema.registerPlugin(new FylrExampleCustomDataModelSettings());
