// Generated by CoffeeScript 1.12.7
var FylrExampleExportPluginSleep,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

FylrExampleExportPluginSleep = (function(superClass) {
  extend(FylrExampleExportPluginSleep, superClass);

  function FylrExampleExportPluginSleep() {
    return FylrExampleExportPluginSleep.__super__.constructor.apply(this, arguments);
  }

  FylrExampleExportPluginSleep.prototype.name = function() {
    return "fylr_example:sleep";
  };

  FylrExampleExportPluginSleep.prototype.nameLocalized = function() {
    return "Sleep";
  };

  FylrExampleExportPluginSleep.prototype.getExportData = function() {
    var exportData;
    exportData = FylrExampleExportPluginSleep.__super__.getExportData.call(this);
    exportData.eas_fields = {};
    if (!exportData.produce_options) {
      exportData.produce_options = {};
    }
    exportData.produce_options.seconds = this.__data.seconds;
    return exportData;
  };

  FylrExampleExportPluginSleep.prototype.renderForm = function() {
    var form;
    this.__data = this.__initData();
    form = new CUI.Form({
      data: this.__data,
      "class": "ez5-example-export-form",
      fields: [
        {
          type: CUI.NumberInput,
          name: "seconds",
          label: "Seconds",
          form: {
            label: "Seconds",
            hint: "How long to sleep the export"
          }
        }
      ]
    });
    return form.start();
  };

  FylrExampleExportPluginSleep.prototype.saveAllowed = function() {
    return true;
  };

  FylrExampleExportPluginSleep.prototype.__initData = function() {
    var data;
    data = {
      seconds: 10
    };
    return data;
  };

  return FylrExampleExportPluginSleep;

})(ExportManagerPlugin);

ez5.session_ready(function() {
  return ExportManager.registerPlugin(new FylrExampleExportPluginSleep());
});
