// Generated by CoffeeScript 1.12.7
var FYLRExampleTransition,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

FYLRExampleTransition = (function(superClass) {
  extend(FYLRExampleTransition, superClass);

  function FYLRExampleTransition() {
    return FYLRExampleTransition.__super__.constructor.apply(this, arguments);
  }

  FYLRExampleTransition.prototype.getListViewColumn = function() {
    return {
      type: CUI.Output,
      text: "Comment"
    };
  };

  FYLRExampleTransition.prototype.getSaveData = function() {
    var sd;
    return sd = {
      type: FYLRExampleTransition.getType(),
      info: {
        comment: "horst"
      }
    };
  };

  FYLRExampleTransition.getType = function() {
    return "fylr_example:set_comment";
  };

  FYLRExampleTransition.getDisplayName = function() {
    return "Comment";
  };

  return FYLRExampleTransition;

})(TransitionActionAction);

TransitionAction.registerAction(FYLRExampleTransition);
